const SAMPLE_PATIENTS = [
  {
    abhaId: "91-4589-2341-9872",
    abhaAddress: "ramesh.patel@abdm",
    name: "Ramesh Patel",
    age: 56,
    gender: "Male",
    phone: "+91 98234 56789",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bloodGroup: "B+",
    primaryLanguage: "Hindi",
    knownRecords: {
      chronicConditions: ["Type 2 Diabetes Mellitus (since 2018)", "Essential Hypertension (since 2020)"],
      allergies: ["Penicillin (Severe Rash/Urticaria)"],
      currentMedications: ["Tab. Metformin 500mg BD", "Tab. Telmisartan 40mg OD", "Tab. Aspirin 75mg OD"],
      pastSurgeries: ["Appendectomy (2014)"],
      lastVisitDate: "2026-06-12",
      lastVisitReason: "Routine 3-month Diabetic follow-up, HbA1c 7.2%",
    },
  },
  {
    abhaId: "42-8812-9034-1123",
    abhaAddress: "priya.sundaram@abdm",
    name: "Priya Sundaram",
    age: 29,
    gender: "Female",
    phone: "+91 97412 34567",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    bloodGroup: "O+",
    primaryLanguage: "Tamil",
    knownRecords: {
      chronicConditions: ["Mild Intermittent Bronchial Asthma"],
      allergies: ["Sulfa Drugs (Sulphonamides)"],
      currentMedications: ["Inhaler Budecort 200mcg (PRN)"],
      pastSurgeries: ["None"],
      lastVisitDate: "2026-03-04",
      lastVisitReason: "Seasonal cough and bronchospasm flare",
    },
  },
  {
    abhaId: "77-3345-6678-0091",
    abhaAddress: "ananya.deshmukh@abdm",
    name: "Ananya Deshmukh",
    age: 44,
    gender: "Female",
    phone: "+91 94220 89123",
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    bloodGroup: "A+",
    primaryLanguage: "Marathi",
    knownRecords: {
      chronicConditions: ["Hypothyroidism (since 2019)", "Migraine (with aura)"],
      allergies: ["No known drug allergies (NKDA)"],
      currentMedications: ["Tab. Thyronorm 50mcg OD (empty stomach)"],
      pastSurgeries: ["Cesarean Section (2016)"],
      lastVisitDate: "2026-05-18",
      lastVisitReason: "TSH monitoring & migraine aura prophylaxis discussion",
    },
  },
  {
    abhaId: "14-9902-3341-7856",
    abhaAddress: "mohammed.zubair@abdm",
    name: "Mohammed Zubair",
    age: 63,
    gender: "Male",
    phone: "+91 98840 12903",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    bloodGroup: "AB+",
    primaryLanguage: "English",
    knownRecords: {
      chronicConditions: ["Ischemic Heart Disease (Stent placed 2021)", "Dyslipidemia"],
      allergies: ["Iodinated Contrast media (flushing/dyspnea)"],
      currentMedications: ["Tab. Atorvastatin 20mg HS", "Tab. Clopidogrel 75mg OD", "Tab. Metoprolol 25mg BD"],
      pastSurgeries: ["PCI with DES to LAD (2021)"],
      lastVisitDate: "2026-07-20",
      lastVisitReason: "Annual Cardiology checkup, Echo EF 52%",
    },
  },
];

module.exports = {
  SAMPLE_PATIENTS
};
